### ISSUE TITLE
Nameplate 0.5.1.0 no longer loads

### ISSUE THREAD

**Issue by qeomash** [Shirk/Nameplate#1]
Windower: 4.4
Nameplate: 0.5.1.0

Latest version of Windower has changed some plugin APIs, so nameplate now just shows an error upon loading:
```
> load nameplate
Error: nameplate - This plugin is out of date. Please download an updated version.
```

**Comment by HealsCodes** [comment]
I'm afraid without actual API docs for plugins there won't be an update. 

Reversing the plugin API for the original version was fun while it lasted.

**Comment by sevu11** [comment]
Seems like there was some update in Windower today as well, the plugin worked on my end until now. 
It sounds like there is little hope to not gonna happen that it will updated without Windower team assistance?

**Comment by VelynM** [comment]
I would hazard a guess that the only thing this needs is a version number bump in Windozer.h, but I am not in a place where I can do that right now.

**Comment by sevu11** [comment]
> What does the link say? Don't have access to discord.

```
Q: With nameplate broke does any fix need to happen from the plugin side??
A: no, but someone is working on a new nameplates plugin/addon
Q: Oh, so  in mean time just update the text to the condensed version with the dat? Not sure how soon this new version will be. I only noticed cause i decided to restart PC... Somehow my VS Code windows and junk reset as well... lol

A: yeah, idk how long it will be but i dont suspect much longer
A2 (probably person making it): I'd just bear with it until the new plugin is out soon™️
it will be in the launcher
```

**Comment by VelynM** [comment]
> I would hazard a guess that the only thing this needs is a version number bump in Windozer.h, but I am not in a place where I can do that right now.

that and a settings struct layout change

is this supposed windower clone plugin released yet?
